--Espanhol es
INSERT INTO languages (locale, messagekey,messagecontent) VALUES
('es', 'cem' , 'cien ' ),
('es', 'cento' , 'por ciento' ),
('es', 'duzentos' , 'doscientos ' ),
('es', 'trezentos' , 'trescientos' ),
('es', 'quatrocentos' , 'cuatrocientos ' ),
('es', 'quinhetos' , 'quintos' ),
('es', 'seiscentos' , 'seiscientos' ),
('es', 'setecentos' , 'setecientos' ),
('es', 'oitocentos' , 'ochocientos' ),
('es', 'novecentos' , 'novecientos' ),
('es', 'vinte' , 'veinte' ),
('es', 'trinta' , 'treinta' ),
('es', 'quarenta' , 'cuarenta' ),
('es', 'cinquenta' , 'cincuenta' ),
('es', 'sessenta' , 'sesenta' ),
('es', 'setenta' , 'setenta' ),
('es', 'oitenta' , 'ochenta' ),
('es', 'noventa' , 'noventa' ),
('es', 'um' , 'uno ' ),
('es', 'dois' , 'dos' ),
('es', 'três' , 'Tres' ),
('es', 'quatro' , 'cuatro' ),
('es', 'cinco' , 'cinco' ),
('es', 'seis' , 'seis' ),
('es', 'sete' , 'Siete ' ),
('es', 'oito' , 'ocho' ),
('es', 'nove' , 'nueve' ),
('es', 'mil' , 'mil' ),
('es', 'dez' , 'diez' ),
('es', 'onze' , 'once ' ),
('es', 'doze' , 'doce' ),
('es', 'treze' , 'trece' ),
('es', 'quatorze' , 'catorce' ),
('es', 'quinze' , 'quince' ),
('es', 'dezesseis' , 'dieciséis ' ),
('es', 'dezessete' , 'de diecisiete' ),
('es', 'dezoito' , 'Dieciocho' ),
('es', 'dezenove' , 'diecinueve' ),
('es', 'e' , 'y' ),
('es', 'zero' , 'cero' ),
('es', 'menos' , 'menos' )
;