--Chinês zh
INSERT INTO languages (locale, messagekey,messagecontent) VALUES
('zh', 'cem' , '一百' ),
('zh', 'cento' , '百分' ),
('zh', 'duzentos' , '兩百' ),
('zh', 'trezentos' , '三百' ),
('zh', 'quatrocentos' , '四百' ),
('zh', 'quinhetos' , '五分之二' ),
('zh', 'seiscentos' , '六百' ),
('zh', 'setecentos' , '七百' ),
('zh', 'oitocentos' , '八百' ),
('zh', 'novecentos' , '九百' ),
('zh', 'vinte' , '二十' ),
('zh', 'trinta' , '三十' ),
('zh', 'quarenta' , '四十歲' ),
('zh', 'cinquenta' , '五十歲' ),
('zh', 'sessenta' , '六十' ),
('zh', 'setenta' , '七十' ),
('zh', 'oitenta' , '八十' ),
('zh', 'noventa' , '九十' ),
('zh', 'um' , '一' ),
('zh', 'dois' , '二' ),
('zh', 'três' , '三' ),
('zh', 'quatro' , '四' ),
('zh', 'cinco' , '五' ),
('zh', 'seis' , '六' ),
('zh', 'sete' , '七 ' ),
('zh', 'oito' , '八' ),
('zh', 'nove' , '九點' ),
('zh', 'mil' , '一千' ),
('zh', 'dez' , '十' ),
('zh', 'onze' , '十一' ),
('zh', 'doze' , '十二點' ),
('zh', 'treze' , '十三' ),
('zh', 'quatorze' , '十四 ' ),
('zh', 'quinze' , '十五' ),
('zh', 'dezesseis' , '十六歲' ),
('zh', 'dezessete' , '十七' ),
('zh', 'dezoito' , '十八' ),
('zh', 'dezenove' , '十九' ),
('zh', 'e' , '和' ),
('zh', 'zero' , '零' ),
('zh', 'menos' , '少一點' )
;