--Alemão de
INSERT INTO languages (locale, messagekey,messagecontent) VALUES
('de', 'cem' , 'einhundert' ),
('de', 'cento' , 'Prozent' ),
('de', 'duzentos' , 'zweihundert' ),
('de', 'trezentos' , 'dreihundert' ),
('de', 'quatrocentos' , 'vierhundert' ),
('de', 'quinhetos' , 'Fünftel' ),
('de', 'seiscentos' , 'sechshundert' ),
('de', 'setecentos' , 'siebenhundert' ),
('de', 'oitocentos' , 'Acht hundert' ),
('de', 'novecentos' , 'neun hundert' ),
('de', 'vinte' , 'zwanzig' ),
('de', 'trinta' , 'dreißig' ),
('de', 'quarenta' , 'vierzig' ),
('de', 'cinquenta' , 'fünfzig' ),
('de', 'sessenta' , 'sechzig' ),
('de', 'setenta' , 'siebzig' ),
('de', 'oitenta' , 'achtzig' ),
('de', 'noventa' , 'neunzig' ),
('de', 'um' , 'einer' ),
('de', 'dois' , 'zwei' ),
('de', 'três' , 'drei' ),
('de', 'quatro' , 'vier' ),
('de', 'cinco' , 'fünf' ),
('de', 'seis' , 'sechs' ),
('de', 'sete' , 'Sieben' ),
('de', 'oito' , 'acht' ),
('de', 'nove' , 'neun' ),
('de', 'mil' , 'tausend' ),
('de', 'dez' , 'zehn' ),
('de', 'onze' , 'elf' ),
('de', 'doze' , 'zwölf' ),
('de', 'treze' , 'dreizehn' ),
('de', 'quatorze' , 'vierzehn' ),
('de', 'quinze' , 'fünfzehn' ),
('de', 'dezesseis' , 'Sechszehn' ),
('de', 'dezessete' , 'siebzehn' ),
('de', 'dezoito' , 'achtzehn' ),
('de', 'dezenove' , 'neunzehn' ),
('de', 'e' , 'und' ),
('de', 'zero' , 'Null' ),
('de', 'menos' , 'nicht weniger' )
;