--Inglês en-US
INSERT INTO languages (locale, messagekey,messagecontent) VALUES
('en', 'cem' , 'one hundred' ),
('en', 'cento' , 'one hundred' ),
('en', 'duzentos' , 'two hundred' ),
('en', 'trezentos' , 'three hundred' ),
('en', 'quatrocentos' , 'four hundred' ),
('en', 'quinhetos' , 'fifths' ),
('en', 'seiscentos' , 'six hundred' ),
('en', 'setecentos' , 'seven hundred' ),
('en', 'oitocentos' , 'eight hundred' ),
('en', 'novecentos' , 'nine hundred' ),
('en', 'vinte' , 'twenty' ),
('en', 'trinta' , 'thirty' ),
('en', 'quarenta' , 'forty' ),
('en', 'cinquenta' , 'fifty' ),
('en', 'sessenta' , 'sixty' ),
('en', 'setenta' , 'seventy' ),
('en', 'oitenta' , 'eighty' ),
('en', 'noventa' , 'ninety' ),
('en', 'um' , 'one' ),
('en', 'dois' , 'two' ),
('en', 'três' , 'three' ),
('en', 'quatro' , 'four' ),
('en', 'cinco' , 'five' ),
('en', 'seis' , 'six' ),
('en', 'sete' , 'Seven' ),
('en', 'oito' , 'eight' ),
('en', 'nove' , 'nine' ),
('en', 'mil' , 'thousand' ),
('en', 'dez' , 'ten' ),
('en', 'onze' , 'eleven' ),
('en', 'doze' , 'twelve' ),
('en', 'treze' , 'thirteen' ),
('en', 'quatorze' , 'fourteen' ),
('en', 'quinze' , 'fifteen' ),
('en', 'dezesseis' , 'sixteen' ),
('en', 'dezessete' , 'seventeen' ),
('en', 'dezoito' , 'eighteen' ),
('en', 'dezenove' , 'nineteen' ),
('en', 'e' , 'and' ),
('en', 'zero' , 'zero' ),
('en', 'menos' , 'minus' )
;