--Francês fr
INSERT INTO languages (locale, messagekey,messagecontent) VALUES
('fr', 'cem' , 'cent' ),
('fr', 'cento' , 'pour cent' ),
('fr', 'duzentos' , 'deux cent' ),
('fr', 'trezentos' , 'trois cents' ),
('fr', 'quatrocentos' , 'quatre cents' ),
('fr', 'quinhetos' , 'cinquièmes' ),
('fr', 'seiscentos' , 'six cent' ),
('fr', 'setecentos' , 'sept cent' ),
('fr', 'oitocentos' , 'huit cent' ),
('fr', 'novecentos' , 'neuf cent' ),
('fr', 'vinte' , 'vingt' ),
('fr', 'trinta' , 'trente' ),
('fr', 'quarenta' , 'quarante' ),
('fr', 'cinquenta' , 'cinquante' ),
('fr', 'sessenta' , 'soixante' ),
('fr', 'setenta' , 'soixante-dix' ),
('fr', 'oitenta' , 'quatre-vingts' ),
('fr', 'noventa' , 'quatre vingt dix' ),
('fr', 'um' , 'une' ),
('fr', 'dois' , 'deux' ),
('fr', 'três' , 'Trois' ),
('fr', 'quatro' , 'quatre' ),
('fr', 'cinco' , 'cinq' ),
('fr', 'seis' , 'six' ),
('fr', 'sete' , 'Sept' ),
('fr', 'oito' , 'huit' ),
('fr', 'nove' , 'neuf' ),
('fr', 'mil' , 'mille' ),
('fr', 'dez' , 'Dix' ),
('fr', 'onze' , 'Onze' ),
('fr', 'doze' , 'Douze' ),
('fr', 'treze' , 'treize' ),
('fr', 'quatorze' , 'Quatorze' ),
('fr', 'quinze' , 'quinze' ),
('fr', 'dezesseis' , 'seize ans' ),
('fr', 'dezessete' , 'dix-sept' ),
('fr', 'dezoito' , 'dix-huit' ),
('fr', 'dezenove' , 'dix-neuf' ),
('fr', 'e' , 'et' ),
('fr', 'zero' , 'zéro' ),
('fr', 'menos' , 'pas moins' )
;